language: php

matrix:
  include:
    - php: 7.1

before_install:
    - composer selfupdate

install:
    - composer update --no-scripts --no-interaction

script:
    - bin/simple-phpunit -c phpunit.xml.dist

env:
    global:
        - secure: Ee71DGvdFZJa0e+YlK5ZfaJgixN+BB2ZrTsodX1gAT27wQT7LkFGc8Ccdatly3GcGF1ZvyGibs+zj0Vm87V3QV6PSO8b0qqdPosd0F344BLaIev/pZkkGILNEQSgmKrJZjEUf5k9rEfrZzWqJ/p6WJkcR8IoNoOYEOvpjoxoixLzKTIe0Nnd/93flxqaiKintxHIMQrNBZBTI7HhOn6mIQCDuEEyPSchq6QGa8ziaiSKQ3yiOtNV4qZ7R+7ArayY/fI3sIGlX4xgDY2yME158xhmAOqHxw3PVxLUvVWU1psh7G7uEFHHVxrOTuKNW1vC7CiZI1gZbL0f+FLSusyCNb7KVPiJ2HsdeLna2lzooLIkf6RkhFyEEq8Rzp2lKl8rt5TLveN0MRTbTBYF8xpSEzPD8NzeJFvGxPHS5DWZD3yQrzJb6+0T858mXHBGbt6IlNCguAKVUVVC8eV6LqexpqbpAc8l4C2AEokIV9o4QOzFWUtzru+C+Guq3cbpxaKuBruI5YQiNmoghWX3W2eYGtoraozDqMhPnvKBu26bGtcRQJwWTyXOJnnHzEFwomI/4qWivrKiQKm/CDfrvCKYtT30zgIqF0p3jV+VY52AjmGQR/cPA0WE/Li3Knath2lUYfypzpu8H+bsTNLmwG5SFl3IMekeJokjzp8sW/aNG9o=
        - secure: desCxE/WnI81ppL4+REW0oop4wU83EE4pmj0dTTGdEpO4CYW0QgBvY/sV3hZMkjzB50atbVmQbPdq+b6f2Mw2s+bpwx5KwOrkD62JRLropl/+5Ug8N0VuVbYR080xjbeXBUY7h+eWva65GtA+4sdsVDoweHMGd4BKfn9luAA7RokjINAKdS/GRXYdfW/JPWp0cwnQm3zjD86xUWN6TioVzrtyBIO72Yeip4JDX4yFG5jrZZw/h4azfIhJNcy1kgzKG4toN1vNvLdU7S43tKzPj8KfJhx+5iUxeFGkLL9+NOSatkDJos1gvcF8+FQStx8eXdv465b+mz1+h+Rawub9porCCx3wT0K8ZH8JnDmrWZmJa2Ps+f/CDdeU0uXLUvW/Au4Xv2h5fZHn1Q2/75n+XTIGBz1nbQFXe24YiEiOQ97rbi5N/FHdrqNtgcgOLXcmxZ1tFp6FJqlowlXQw4GchihvMfposAlXQTDoaOad17ij9kqWgPyrVGeBa0353bzDs9O5mD20tK20LgNPd+xi5jBsoMHBaActUV1jqklw7t6LdR8yuT/KrlRZdvKO4vmU7LRLsZ2v8oJPen0iAMtnNluyiZRhswgjZ38taPqdd0qJZMhULFjoy/H8C9a76TuxdBJi8ve4NhUhifBqZ8GH8vMkkdAVHF3fnQmIuNSXKs=
